### ISSUE TITLE
track license denials

### ISSUE THREAD

**Issue by pfranz** [mjtrangoni/flexlm_exporter#13]
Is there any way to log license DENIALS?  For example, when you're out of licenses and someone makes a request.

**Comment by mjtrangoni** [comment]
Hi @pfranz,

Your question is really good. This information is unfortunately only exposed at the debug logs, and for that reason outside the scope of this project. I would recommend you to use one of this tools,

1. [mtail](https://github.com/google/mtail): extract whitebox monitoring data from application logs for collection in a timeseries database.
2. [Loki](https://grafana.com/loki#about):  Prometheus-inspired logging for cloud natives.
3. [Filebeat](https://www.elastic.co/products/beats/filebeat): Lightweight Shipper for Logs.

Once you have a working solution, I would love to link and/or refer your implemetation here.

**Comment by mjtrangoni** [comment]
Closing. Feel free to reopen
