### ISSUE TITLE
Build Error - undefined: collector.LicenseConfig

### ISSUE THREAD

**Issue by bsener** [mjtrangoni/flexlm_exporter#14]
### Host operating system: output of `uname -a`

Windows Server 2012

### flexlm_exporter command line flags and relevant YAML configuration file information

Default config file
### What did you do that produced an error?
I ran the 'go build' command after running 'go get'. 
### What did you expect to see?
Successful build. (Or if there is an executable it would be great.)
### What did you see instead?
.\flexlm_exporter.go:103:2: undefined: collector.LicenseConfig

**Comment by mjtrangoni** [comment]
@bsener Sorry for the delay. Could you please test if this is building for you on Windows from master branch? 
If yes, please test if it is also working as expected. Thanks!

**Comment by mjtrangoni** [comment]
Closing. Feel free to reopen
