### ISSUE TITLE
How to set up the grafana dashboard?

### ISSUE THREAD

**Issue by ilesser** [mjtrangoni/flexlm_exporter#16]
Hi, first of all thank you for this project it is awesome!

I am very new to grafana and have no experience at all.
I would like to know if you could explain a little bit the steps necessary to import your dashboard so it can be used?

Here's what I've done:
I was able to run flexlm_exporter and I can access the metrics at localhost:9313/metrics  via my web browser.
I installed a grafana server and I am able to login correctly.
I was able to import your dashboard using the ID from grafana website.
But I don't know how to connect them.
I tried creating a new data source of prometheus and configured the url to be localhost:9319/metrics but when I enter the dashboard it says no data.
Is this correct?
should I do something else?

Thank you very much

**Comment by mjtrangoni** [comment]
Hi @ilesser,

Sorry for the delay. You are missing the Prometheus server here. You have to setup one prometheus server, and configure there this exporter. Once you have the metrics on the prometheus server side, you can configure it as a grafana datasource, see [here](https://prometheus.io/docs/visualization/grafana/).

Closing this, but don`t hesitate to re-open if you have another question.

**Comment by ilesser** [comment]
Hi @mjtrangoni ,

I'll give it a try during the week and let you know.
Thanks for the answer!
