### ISSUE TITLE
Alertmanager rule example

### ISSUE THREAD

**Issue by nwies** [mjtrangoni/flexlm_exporter#17]
Hello,

Please find below 2 rules for alertmanager.

groups:
- name: default
  rules:
  #FlexLm Server Down
  - alert: FlexLmServerDown
    expr: flexlm_server_status == 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Flexlm Error (instance {{ $labels.instance }})"
      description: "FlexLm {{ $labels.collector }} was not successful\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    #Licence Fully used
  - alert: LicenceAvailable
    expr: 100*(flexlm_feature_used / flexlm_feature_issued) > 95
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Licence Available Status (instance {{ $labels.instance }})"
      description: "Licence fully used \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

![flexlm_alertmanager_example](https://user-images.githubusercontent.com/10389749/66719739-f84ad380-edf3-11e9-8786-b46289a84b22.png)

**Comment by mjtrangoni** [comment]
Hi @nwies,

Thanks for contribting! See [here](https://github.com/mjtrangoni/flexlm_exporter#prometheus-rules)
