### ISSUE TITLE
Feature expiration problem

### ISSUE THREAD

**Issue by Anmaz82** [mjtrangoni/flexlm_exporter#18]
Dear Mario,

First of all I want to thank you for your great product!

I'am using docker(:master) version of your software, and I have a problem to get feature expiration list.

In /metrics I see that feature - ( flexlm_scrape_collector_success{collector="lmstat_feature_exp"} 1 ) , but no data in prometheus at all regarding features expiration.

Maybe I'am looking at wrong place?
When I doing lmstat -c <licfile> -i i get all feature expiration dates

UPD: I have build from last source version and the same
In prometheus i can see the following metric names (with flexlm_feature_*):
flexlm_feature_issued
flexlm_feature_used
flexlm_feature_used_users

### Host operating system: output of `uname -a`
docker exec -ti 51d3ecfb15e1 uname -a
Linux 51d3ecfb15e1 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### flexlm_exporter version: output of `flexlm_exporter --version`
docker exec -ti 51d3ecfb15e1 flexlm_exporter --version
flexlm_exporter, version 0.0.4 (branch: master, revision: 424b78bc1a89af7337cd9186b290e6bffb536347)
  build user:       circleci@f49bde6e6e27
  build date:       20191111-18:45:23
  go version:       go1.13.4

### flexlm_exporter command line flags and relevant YAML configuration file information
docker run --name flexlm_exporter -d -p 9319:9319 --volume /opt/flexlm/bin/:/usr/bin/flexlm/ --volume $FLMEXP_CONFIG:/config quay.io/mjtrangoni/flexlm_exporter:master --path.lmutil="/usr/bin/flexlm/lmutil" --path.config="/config/licenses.yml"

license.yml
i've tried license_file and license_server configuration both have the same behaviour

### Are you running flexlm_exporter in Docker?
Yes

### What did you do that produced an error?
Nothing special, started flexlm_exporter with docker command

### What did you expect to see?
Feature expiration dates

### What did you see instead?
Nothing, empty neither in grafana and in prometheus

Could you please assist?

Regards,
Anton

**Comment by mjtrangoni** [comment]
Hi @Anmaz82,

Sorry for the late response! Could you please provide here the output of: 

```bash
$ lmutil lmstat -c license_file -i
```
I need to check what`s not matching in your case. You can send it to me via e-mail or attached here if you like to.

Best regards,
Mario

**Comment by Anmaz82** [comment]
Hello Mario,

Thanks for your answer!
I have compiled flexlm_exporter latest version and it's working fine, working version:

flexlm_exporter, version 0.0.4 (branch: master, revision: 424b78bc1a89af7337cd9186b290e6bffb536347)
  build user:       root@<hostname>
  build date:       20191209-14:34:39
  go version:       go1.13.5

Regards,
Anton
