### ISSUE TITLE
Make failing

### ISSUE THREAD

**Issue by mill-systems** [mjtrangoni/flexlm_exporter#19]
### Host operating system: output of `uname -a`
3.10.0-957.5.1.el7.x86_64

### flexlm_exporter version: output of `flexlm_exporter --version`

n/a

### Are you running flexlm_exporter in Docker?
No

### What did you do that produced an error?
Just ran make

### What did you expect to see?
make completes

### What did you see instead?
`>> Cleaning up
>> ensure vendoring
>> formatting code
>> vetting code
>> linting code
collector/lmstat_feature_exp_linux_test.go:30:1: cognitive complexity 66 of func `TestParseLmstatLicenseFeatureExpDate` is high (> 60) (gocognit)
func TestParseLmstatLicenseFeatureExpDate(t *testing.T) {
^
collector/lmstat_linux_test.go:188:1: cognitive complexity 61 of func `TestParseLmstatLicenseInfoFeature` is high (> 60) (gocognit)
func TestParseLmstatLicenseInfoFeature(t *testing.T) {
^
collector/lmstat_feature_exp_linux.go:62:23: mnd: Magic number: 1, in <argument> detected (gomnd)
			expires = math.Inf(1)
			                   ^
collector/lmstat_feature_exp_linux_test.go:78:33: mnd: Magic number: 1, in <argument> detected (gomnd)
				feature.expires != math.Inf(1) ||
				                            ^
collector/lmstat_feature_exp_linux_test.go:88:33: mnd: Magic number: 1, in <argument> detected (gomnd)
				feature.expires != math.Inf(1) ||
				                            ^
collector/lmstat_feature_exp_linux.go:47:18: mnd: Magic number: 1, in <condition> detected (gomnd)
		if len(day) == 1 {
		               ^
collector/lmstat_feature_exp_linux.go:50:19: mnd: Magic number: 1, in <condition> detected (gomnd)
		if len(year) == 1 {
		                ^
collector/lmstat_linux_test.go:213:18: mnd: Magic number: 16, in <condition> detected (gomnd)
			if licused != 16 {
			              ^
collector/lmstat_linux_test.go:219:18: mnd: Magic number: 26, in <condition> detected (gomnd)
			if licused != 26 {
			              ^
collector/lmstat_linux_test.go:224:18: mnd: Magic number: 12, in <condition> detected (gomnd)
			if licused != 12 {
			              ^
collector/lmstat_linux_test.go:239:18: mnd: Magic number: 16, in <condition> detected (gomnd)
			if licused != 16 {
			              ^
collector/lmstat_linux_test.go:245:18: mnd: Magic number: 1, in <condition> detected (gomnd)
			if licused != 1 {
			              ^
collector/lmstat_linux_test.go:250:18: mnd: Magic number: 16, in <condition> detected (gomnd)
			if licused != 16 {
			              ^
collector/lmstat_linux_test.go:298:20: mnd: Magic number: 8, in <condition> detected (gomnd)
			if licreserv != 8 {
			                ^
make: *** [golangci] Error 1
`

**Comment by mjtrangoni** [comment]
Hi @mill-systems,

This should be now fixed on master branch. Could you please test? Feel free to re-open if you find other related issue.
