### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by JulienWegner** [mjtrangoni/flexlm_exporter#22]
First of all I want to thank you for this great project..
I tried to build flexlm_exporter but get an error all the time:

go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding github.com/coreos/etcd v3.3.18+incompatible
go get: error loading module requirements
make: *** [Makefile:85: /home/cem6564/go/bin/golangci-lint] Error 1

Do you have an idea to fix it?

**Comment by mjtrangoni** [comment]
Hi @JulienWegner,
You need to provide me a lot of more information than that for giving you an answer. 
- Do you have a running golang environment?
- Which golang version are you using?
You need 1.13.x for compiling it, as golang modules changed the way they works from version 1.12 to 1.13.
