### ISSUE TITLE
Lmstat parser in a separate library

### ISSUE THREAD

**Issue by yurinnick** [mjtrangoni/flexlm_exporter#25]
Lmstat code looks neat and it would be great to reuse it for other flexlm related projects. Is it possible to move lmstat parsing existing code into a separate library, so it won’t have dependency on prometheus? Thanks!

**Comment by mjtrangoni** [comment]
Hi @yurinnick,
you are right, It would be nice having a golang library for calling flexlm commands like lmstat. But this is out of the scope of this project, as then you would start thinking on supporting other commands, etc. If you are interested in creating that library, I would be happy to integrate it here. Thanks!
