### ISSUE TITLE
Error during parsing expiration date on lic with different expiration date 

### ISSUE THREAD

**Issue by nwies** [mjtrangoni/flexlm_exporter#33]
### Host operating system: output of `uname -a`
Linux localhost.localdomain 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### flexlm_exporter version: output of `flexlm_exporter --version`

flexlm_exporter, version  (branch: master, revision: 0f97863064f040b96d582fc800bfc910dda8f83b)
  build user:       root@localhost.localdomain
  build date:       20200324-09:10:34
  go version:       go1.14
Last version cloned before reporting the issue
### Are you running flexlm_exporter in Docker?
No
### What did you do that produced an error?
having same lic in multiple expiration date : 8 permanent  + 2 expiring April 30th 2020
### What did you see instead?
error message:
flexlm_exporter[20441]: time="2020-03-24T09:12:59Z" level=error msg="could not convert to date: parsing time \"30-Apr-20202\": extra text: 2" source="lmstat_feature_exp_linux.go:78"

Please find the lmstat file
[lmstat_multiple_lic_expiration.txt](https://github.com/mjtrangoni/flexlm_exporter/files/4374322/lmstat_multiple_lic_expiration.txt)

**Comment by nwies** [comment]
add the metrics expo
[lmstat_multiple_lic_expiration_metrics.txt](https://github.com/mjtrangoni/flexlm_exporter/files/4374349/lmstat_multiple_lic_expiration_metrics.txt)
rted

**Comment by nwies** [comment]
add the /var/log/messages with flexlm_exporter in "debug" mode
[message_log_debug.txt](https://github.com/mjtrangoni/flexlm_exporter/files/4379122/message_log_debug.txt)

**Comment by nwies** [comment]
I look into the log message and I think I found the problem.
Only some features have an error message ("prd_common 2lic " but not "prd_common 8lic").
there is a counter for each feature numbers. For a permanent lic, no problem because the exporter parse the lmstat output and the counter correctly:

"[prd_common                      15.0         2           ugslmd        30-apr-2020 prd_common 15.0 2 ugslmd 30-apr-2020]"
"[prd_common                      15.0         2           ugslmd        30-apr-2020**2** prd_common 15.0 2 ugslmd 30-apr-2020**2**]"
"[prd_common                      15.0         8           ugslmd        permanent(no expiration date) prd_common 15.0 8 ugslmd permanent(no expiration date)]"
"[prd_common                      15.0         8           ugslmd        permanent(no expiration date)**2** prd_common 15.0 8 ugslmd permanent(no expiration date)**2**]"
"[prd_common                      15.0         8           ugslmd        permanent(no expiration date)**3** prd_common 15.0 8 ugslmd permanent(no expiration date)**3**]"

Could you please add a space between this counter and the expiration date ?

**Comment by mjtrangoni** [comment]
@nwies,
Sorry for the delay. Where does that `30-Apr-20202` comes from?

**Comment by nwies** [comment]
Hello,

It's the correct date April 30th 2020 and maybe the number of lic expiring
{2}.

I don't have any other numbers lic expiring for the moment

Le ven. 10 avr. 2020 à 15:48, Mario Trangoni <notifications@github.com> a
écrit :

**Comment by dekoenpi** [comment]
Hello,

first thank your for making this great exporter!
I have the same problem on my site. Used newest image mjtrangoni/flexlm_exporter:master

**docker-compose logs:**

`flexlm-exporter    | time="2020-10-08T06:25:21Z" level=error msg="could not convert to date: parsing time \"30-Jul-20212\": extra text: 2" source="lmstat_feature_exp_linux.go:78"

flexlm-exporter    | time="2020-10-08T06:25:21Z" level=error msg="could not convert to date: parsing time \"30-Jul-20212\": extra text: 2" source="lmstat_feature_exp_linux.go:78"

flexlm-exporter    | time="2020-10-08T06:25:21Z" level=error msg="could not convert to date: parsing time \"30-Jul-20212\": extra text: 2" source="lmstat_feature_exp_linux.go:78"

flexlm-exporter    | time="2020-10-08T06:25:36Z" level=error msg="could not convert to date: parsing time \"30-Jul-20212\": extra text: 2" source="lmstat_feature_exp_linux.go:78"

flexlm-exporter    | time="2020-10-08T06:25:36Z" level=error msg="could not convert to date: parsing time \"30-Jul-20212\": extra text: 2" source="lmstat_feature_exp_linux.go:78"`


seems this app:

**Prometheus execute:**
**flexlm_feature_expiration_seconds**

flexlm_feature_expiration_seconds{app="CAM350",index="1",instance="flexlm-exporter:9319",job="flexlm-exporter",licenses="2",name="CAM350-620",vendor="act_inc",version="2020.11"}

Value: 1622505600

Best regards

**Comment by 99rgosse** [comment]
Hello, and thanks for this exporter tool & the Grafana dashboard 👍 

I got the same issue than @dekoenpi and I was wondering if it's not because of the locale settings ?
I forked your project and will try to test this :)
Thanks again !

**Comment by 99rgosse** [comment]
While I'm not sure from where the extra digit come, I added this hideous workaround
https://github.com/99rgosse/flexlm_exporter/blob/55b36eae63ea5a48429cde5df6c4834d89c82d40/collector/lmstat_feature_exp_linux.go#L68

and got the exporter to run
Feel free to comment if I can help in any case...

**Comment by mjtrangoni** [comment]
@99rgosse thanks for debugging this problem. Can you send me a PR so that we can integrate the fix to the project? Thanks!

**Comment by 99rgosse** [comment]
With

> @99rgosse thanks for debugging this problem. Can you send me a PR so that we can integrate the fix to the project? Thanks!

With pleasure !! Later, when possible, I will see also to anonymize my licence file so that we can add it to the fixtures tests :)

**Comment by mjtrangoni** [comment]
Closed via #44. Thanks @99rgosse
