### ISSUE TITLE
What are the pre-reqs?

### ISSUE THREAD

**Issue by juzza88** [mjtrangoni/flexlm_exporter#35]
Any chance you can give us a list of what is need to get this going?

Centos host with docker?
golang configured?

what else is needed? none of your steps work right now

**Comment by mjtrangoni** [comment]
Hi @juzza88,
such issues are not necessary. You are opening an issue on an open source project, and not getting paid enterprise support. 
Please read always the documentation before,

- Golang: https://golang.org/doc/install
- Prometheus: https://prometheus.io/docs
- Grafana: https://grafana.com/docs/grafana/latest/

After that, please follow the Issue template I take the time to do.

Thanks!

**Comment by juzza88** [comment]
even the pull doesnt work


PS C:\> docker pull quay.io/mjtrangoni/flexlm_exporter
Using default tag: latest
docker : Error response from daemon: manifest for quay.io/mjtrangoni/flexlm_exporter:latest not found: manifest unknown: manifest unknown
At line:1 char:1
+ docker pull quay.io/mjtrangoni/flexlm_exporter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...anifest unknown:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
