### ISSUE TITLE
Feature request: list of features

### ISSUE THREAD

**Issue by HavivEderi** [mjtrangoni/flexlm_exporter#38]
Hi,

I think it will be really useful to write a function that return all feature names and feature names per app.
Sadly because that you use field "name" for features, when query Prometheus for "/api/v1/label/name/values" i get app and vendor names as well as feature names.
I think the root cause is because you use "name" field in flexlm_vendor_status and flexlm_scrape_error.
So it will be cool either if you fix it by changing the field name or add another function that handles feature names.

Let me know what you think.
Thanks.

**Comment by mjtrangoni** [comment]
@HavivEderi can you elaborate a little bit more here with examples?

**Comment by mjtrangoni** [comment]
this seems stale, closing for now. Feel free to reopen.
