### ISSUE TITLE
scrape collector issu over time

### ISSUE THREAD

**Issue by nwies** [mjtrangoni/flexlm_exporter#4]
### Host operating system: output of `uname -a`
CentOS Linux release 7.4.1708 (Core)
Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### flexlm_exporter version: output of `flexlm_exporter --version`

flexlm_exporter, version 0.0.1 (branch: master, revision: df8de569d92350b4cf04e1a79990b07f781cb524)
  build user:       root@localhost.localdomain
  build date:       20180222-17:37:07
  go version:       go1.8.3

### flexlm_exporter command line flags and relevant YAML configuration file information

Command line
/usr/bin/flexlm_exporter --path.lmutil=/usr/bin/lmutil --path.config=/etc/prometheus/flexlm_exporter.yaml

yaml file

####
# FlexLM Licenses to be monitored.
---
licenses:

  - name: abbrcs_Trappes
    license_server: 27000@UFRTR1DT0070021.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: kukarcs_Castres
    license_server: 27001@UFRCAS01LMRP010.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: Tecno_Castres
    license_server: 27006@UFRCAS01LMRP010.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: Xelec_Castres
    license_server: 18000@UFRCAS01LMRP010.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: PS_Castres
    license_server: 28000@UFRCAS01LMRP020.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##

####
prometheus.yaml flex_lm part

  - job_name: 'flexlm'
    scrape_interval: '15s'
    static_configs:
      - targets: ['localhost:9319']
####

### Are you running flexlm_exporter in Docker?
No
I'm using prometheus in order to monitor the few lic server and 25 windows server with wmi_exporter (who don't show any blanks so not seem related to the prometheus server )
### What did you do that produced an error?
I'm loosing several scrape
if I looking into "flexlm_scrape_collector_success" there is some "zero" value over time
There is 2 grafana dashboard extract over the last 3hours and the scrape duration (ever less than scrape intervals)

### What did you expect to see?
a full constant line

### What did you see instead?
some blanks
![scrape_duration](https://user-images.githubusercontent.com/10389749/39204487-33d23144-47f8-11e8-80b6-3822b189d061.png)
![chrome_2018-04-24_19-41-47](https://user-images.githubusercontent.com/10389749/39204489-33f9233a-47f8-11e8-9e5e-de080b6186b9.png)
![chrome_2018-04-24_19-41-36](https://user-images.githubusercontent.com/10389749/39204490-341ac3be-47f8-11e8-9f89-9cbf39c77859.png)

**Comment by mjtrangoni** [comment]
Hi @nwies, 
Thanks for reporting! I would personally recommend you to use `scrape_interval: '30s'` or even `60s`, as this highest frequency(15s) is not going to give you much more resolution.

Do you see already any warning/error message produced by the `flexlm_exporter` in `dmesg` or `journalctl`? If not, could you please run the `flexlm_exporter` with `--log.level="debug"` for a while and then check if any error shows up?

**Comment by nwies** [comment]
Hello,

 i check dmesg And journalctl And i don't see any warning for flexlm
exporter.
But I still see blank in grafana this morning.

 I will switch to 30 s scrap for the day in order check if the blanks still
appear.

Keep you posted.

BR

Le mar. 24 avr. 2018 22:31, Mario Trangoni <notifications@github.com> a
écrit :

**Comment by nwies** [comment]
hello, I setup the debug log level and the 30s scrape. even with this last parameter (30s) I still see blank
[log_flexlm_exporter_2018_04_25_1330.txt](https://github.com/mjtrangoni/flexlm_exporter/files/1946806/log_flexlm_exporter_2018_04_25_1330.txt)

on the debug log, the lmstat is always successfull on around 10s
What could be the next move?

Thanks for your help.
BR

**Comment by nwies** [comment]
Thanks for the tips. I put the ip adress for this server on the flexlm_exporter.yml. 
We will see after few hours.

**Comment by nwies** [comment]
still the same, but no error from the debug log ...
![scrape_success_20180426](https://user-images.githubusercontent.com/10389749/39316464-836911be-4979-11e8-9646-6ecd6b77328b.png)
[log_flexlm_exporter_2018_04_26.txt](https://github.com/mjtrangoni/flexlm_exporter/files/1951930/log_flexlm_exporter_2018_04_26.txt)

What could we try now ?
maybe add the flexlm server one by one ?

**Comment by mjtrangoni** [comment]
@nwies mmm, could you take a look, and see which of all you license metrics are missing. With this dashboard [here](https://grafana.com/dashboards/3854), you can narrow it down.

In my production instances I see from time to time some failing scrapes, but it always has something to do with a  FlexLM daemon reload for configuration changes or system maintenance.

**Comment by mjtrangoni** [comment]
@nwies ping

**Comment by nwies** [comment]
hello,

Sorry for not responding before, i was on long weekend.
today,  I set the exporter oto listen only on the flex server on the same
lan.
I will look at the results tomorrow afternoon.


Do you think the exporter could trash all the datas from the current scrape
if a server will not send his infos?

Br


Le mer. 2 mai 2018 11:35, Mario Trangoni <notifications@github.com> a
écrit :

**Comment by nwies** [comment]
hello, I just look into the grafana reprot and no problem with the server from the same lan.
I setup another flexlm server (windows 2012) from another lan.
cross finger it will be the last and old one (windows 203) causing trouble.

BR

**Comment by nwies** [comment]
hello,
I just look at the grafana and no problem with the second flexlm server. So, the old windows server should be the problem.
Is there a way to not have the complete scape invalidated if any server do not respond?

BR

**Comment by mjtrangoni** [comment]
@nwies If some FLEXlm license fails, you should be still getting the information from the other licenses. This exporter scrape every license individually with `lmutil lmstat -c <port>@<fqdn> -a`, so if this fails, the individual scrape will be failing and not everyone.

You could configure more than just one `flexlm_exporter` instance, ie. one per LAN.

**Comment by nwies** [comment]
ok. I will do.
Thanks for your help.

the issue as not related to your exporter and it can be close now.
