### ISSUE TITLE
multi server example expected result is what?

### ISSUE THREAD

**Issue by woodshop2300** [mjtrangoni/flexlm_exporter#40]
In the readme configuration example mutiple servers are specified
`license_server: 28000@host1,28000@host2,28000@host3`
What is the expected result of doing this?

Expanded:
I have one weird case in my environment where i have the licenses for a product split between 2 servers.
These servers aren't aware of each other, they aren't a primary/backup configuration.
When i attempted to use the above syntax to try and poll both servers, thinking some kind of aggregation would happen, what i got instead was a report on only whichever server i listed first.
I went browsing through the code and as best i can tell the list of servers is just sent to lmutil as is without any modification and the codes not doing any kind of looping.
So i went to calling lmutil directly with the list of servers and sure enough i only get a report back for the first server listed and no indication of any kind of error, if i flip the order of the servers in the lmutil line the server thats reported on changes. So its really just the first one.

```
./bin/lmutil -v
Copyright (c) 1989-2018 Flexera. All Rights Reserved.
lmutil v11.16.2.1 build 244538 x64_lsb
```

**Comment by mjtrangoni** [comment]
Hi @woodshop2300,

Yes, you are right. The idea is that if the first server fails, the exporter will pick the second one, as they are supposed to serve the same license. This is a license triple configuration, that allow you to reboot for maintenance.

In your case, you need to define 2 different licenses, as they are no the same one.

**Comment by woodshop2300** [comment]
Alright, i had my suspicions it would be something like that.
