### ISSUE TITLE
Docker scraper gives no results

### ISSUE THREAD

**Issue by JSP80** [mjtrangoni/flexlm_exporter#45]
### Host operating system: output of `uname -a`
Linux 1ea449ced488 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### flexlm_exporter version: output of `flexlm_exporter --version`
flexlm_exporter, version 0.0.5-13-gd08149b (branch: master, revision: d08149b1ce29e28dc16c3f3a87d5eae61fe929fd)
  build user:       circleci@a56f76e7ba6d
  build date:       20201219-14:50:13
  go version:       go1.15.6
  platform:         linux/amd64

### flexlm_exporter command line flags and relevant YAML configuration file information

--path.lmutil=/usr/bin/flexlm/lmutil --path.config=/config/licenses.yml

yaml:
### FlexLM Licenses to be monitored.
---
licenses:
  - name: NX TC Licserver
    license_file: 28000@--redacted--
    features_to_exclude:
    monitor_users: True
    monitor_reservations: True
  - name: Test NX TC Licserver
    license_file: 28000@--redacted--
    features_to_exclude:
    monitor_users: True
    monitor_reservations: True

### Are you running flexlm_exporter in Docker?
Yes
### What did you do that produced an error?
There is no error. Only no metrics are scraped.
### What did you expect to see?
Metrics

### What did you see instead?
No data flowing to Prometheus

### Other information
I do have a self compiled flexlm_exporter windows scraper running and that is functioning as it should. But now running from docker I can't get it to work. 
metrics page from docker:
![image](https://user-images.githubusercontent.com/62709893/104198351-6bdbf600-5426-11eb-9a58-32ec1cf4de62.png)

metrics page from windows version
![image](https://user-images.githubusercontent.com/62709893/104198553-a3e33900-5426-11eb-86e5-e49560a59506.png)

If I run in Docker CLI lmutils lmstat -c 28000@licenseserver -a I get a response that license server is down or not responding.
lmstat -v gives result. License server host is also reachable from docker cli.

**Comment by mjtrangoni** [comment]
@JSP80 Did you debug why `lmutils lmstat -c 28000@licenseserver -a` says it is down inside of docker? You need to find that out.
