### ISSUE TITLE
Feature request: Add hostnames to Prometheus

### ISSUE THREAD

**Issue by JSP80** [mjtrangoni/flexlm_exporter#46]
#### Thanks for the great tool. 
Is it possible to add Hostnames to the results in Prometheus. If I do lmstat -c ....@.... -v I get a result like this:
Users of Nxhxhxhhx:  (Total of 78 licenses issued;  Total of 33 licenses in use)
____
  "Nxhxhxhhx" v36.0, vendor: notapplicable, expiry: 1-jan-0
  floating license

    edengineer EDSCLIENT03 EDSCLIENT030.0 (v36.0) (licserver/28000 24025), start Tue 1/5 15:15
___

So I would like in above example the second column (EDSCLIENT03) also added to the metrics.

**Comment by mjtrangoni** [comment]
@JSP80 it is possible, but it is an antipattern, as the number of labels would explode, and also the number of stale labels would grow exponentially. See [this](https://www.robustperception.io/cardinality-is-key).
