### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by FaziXX** [mjtrangoni/flexlm_exporter#54]
Hello,

I have this error since 4 days

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x893130]

goroutine 12 [running]:
github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoServer(0xc00012a780, 0x1a, 0x1a, 0xc00012a780)
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:135 +0x5b0
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc000262240, 0xc00018e840, 0x0, 0x0)
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:292 +0x21f
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc000262240, 0xc00018e840, 0xdedf80, 0x50)
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:99 +0xcb
github.com/mjtrangoni/flexlm_exporter/collector.execute(0x9b3d04, 0x6, 0xa67500, 0xc000262240, 0xc00018e840)
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:140 +0x7e
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc00018e840, 0xc0000258b0, 0x9b3d04, 0x6, 0xa67500, 0xc000262240)
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:126 +0x53
created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
        /root/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:125 +0x109
-->
### Host operating system: output of `uname -a`
4.18.0-240.el8.x86_64 #1 x86_64 GNU/Linux
(base) [root@sc2-watcher files]# /usr/local/bin/flexlm_exporter --version
flexlm_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.13.6

### flexlm_exporter command line flags and relevant YAML configuration file information
/path/to/flexlm_exporter --path.config=/path/to/licence.yml --path.lmutil=/path/to/lmutil

### Are you running flexlm_exporter in Docker?
no
### What did you do that produced an error?
nothing

### What did you seef instead?
[error.txt](https://github.com/mjtrangoni/flexlm_exporter/files/8333255/error.txt)

**Comment by mjtrangoni** [comment]
Hi @FaziXX,

Sorry for the delay. I see your Golang version is pretty outdated. Can you try to build with at least go 1.17.x?

FYI, see this from the Golang documentation, https://go.dev/doc/devel/release,

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

That is why, this project is focused on the same target.
