### ISSUE TITLE
flexlm_exporter: error: unknown long flag '--path.lmutil'

### ISSUE THREAD

**Issue by cloudrck** [mjtrangoni/flexlm_exporter#77]
### Host operating system: output of `uname -a` 
`Linux 4.18.0-477.15.1.el8_8.x86_64 #1 SMP Fri Jun 2 08:27:19 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux` AND `Linux 9dcd4af67bcb 6.1.49-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Aug 27 23:08:04 UTC 2023 x86_64 GNU/Linux`

### flexlm_exporter version: output of `flexlm_exporter --version`
```
flexlm_exporter, version  (branch: non-git, revision: non-git)
  build user:       me@
  build date:       20230921-21:19:53
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo static_build
```

### flexlm_exporter command line flags and relevant YAML configuration file information

```
--path.config="/opt/flexlm_exporter/licenses.yml" \
    --path.lmutil="/opt/flexlm_exporter/lmutil" \
    --log.level=debug
```

### What did you do that produced an error? 
Built latest master branch code as of today (Sept 21, 2023) using Go 1.20

### What did you expect to see? 
license data

### What did you see instead? Error

Because of the issues I'm having with #76, I decided to build the latest code using the latest Go version.

It builds fine. However, the exporter never actually runs. If I provide the path to lmutil, it gives the error:
```
flexlm_exporter: error: unknown long flag '--path.lmutil', try --help
```

If I remove the path, and try to place the lmutil binary in the "default path" as show in:
https://github.com/mjtrangoni/flexlm_exporter/blob/5fe9f8cead9ea7db2924fef55759f6d3f3b66ff1/collector/paths.go#L22

My assumption is that `flexnet` folder is in the same folder of flexlm_exporter binary. However, nothing appears to happen. No error messages, but no license data or metrics exporting

**Comment by mjtrangoni** [comment]
@cloudrck good catch! Thanks for reporting!
