### ISSUE TITLE
RESERVATION for HOST 

### ISSUE THREAD

**Issue by plustig73** [mjtrangoni/flexlm_exporter#84]
### Host operating system: output of `uname -a`

Windows

### flexlm_exporter version: output of `flexlm_exporter --version`

D:\Source\FlexLM_Exporter>flexlm_exporter.exe --version
flexlm_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.19
  platform:         windows/amd64

### flexlm_exporter command line flags and relevant YAML configuration file information

flexlm_exporter.exe --log.level=debug --path.lmutil="D:\Source\FlexLM_Exporter\lmutil.exe"  --path.config="D:\Source\FlexLM_Exporter\licenses.yml" --web.disable-exporter-metrics

  - name: SolidWorks-Licenses
    license_server: 12345@Licenserver
    features_to_include: solidworks
    monitor_users: True
    monitor_reservations: True
    monitor_versions: True

### Are you running flexlm_exporter in Docker?

No

### What did you expect to see?

Also the Reservations for Hosts

### What did you see instead?

Only Reservations for Groups
______________________________________

Hello, is it possible to get also the Reservations for Hosts?

It looks like this after a lmutil lmstat -c 12345@Licenserver -a 

"solidworks" v31.0, vendor: SW_D
floating license

1 RESERVATION for HOST HOSTPC1 (licenserver/25734)
1 RESERVATION for HOST HOSTPC2 (licenserver/25734)
1 RESERVATION for HOST HOSTPC3 (licenserver/25734)
11 RESERVATIONs for GROUP DESIGN_DEPT (licenserver/25734)
1 RESERVATION for GROUP DOC_ELD_DEPT (licenserver/25734)

The Reservations for Groups are working.

Thanks

BR

Roland

**Comment by plustig73** [comment]
HI, thanks for your fast answer.

I do not mean a HOST_GROUP, but "individual" reservations for a single HOST.

In the options file, for example, it looks like this:

RESERVE 1 solidworks HOST HOST1251
RESERVE 1 solidworks HOST HOST1252
RESERVE 1 solidworks HOST HOST1254
RESERVE 1 solidworks HOST HOST1258

(so for each of this HOSTS 1 license is reserved).

If you need more information please do not hesitate to ask me any questions.

BR

Roland

**Comment by mjtrangoni** [comment]
Hi @plustig73,

I gave it a try and implemented it [here](https://github.com/mjtrangoni/flexlm_exporter/tree/reserve_by_host). Would you mind building from reserve_by_host and give it a try?

Thank you!

**Comment by plustig73** [comment]
Hello Mario @mjtrangoni , 

i´m not sure how to test this. Is there a new version of the flexlm_exporter.exe to test this? 

Unfortunately i don't know anything about compiling and things like that.

BR

Roland

**Comment by mjtrangoni** [comment]
resolved via #104 and `v0.0.12`
